name: Sync to Gitee

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-th-dd:
    name: Sync th-dd
    runs-on: ubuntu-latest
    steps:
      - name: Mirror th-dd
        uses: Yikun/hub-mirror-action@ba51c01b28a6c9f95a25d4f1bcf6af2a147c0e18
        with:
          src: github/th-dd
          dst: gitee/ya2
          src_account_type: user
          dst_account_type: user
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          src_token: ${{ secrets.SRC_TOKEN }}
          static_list: "th-dd,npmjs-chinese"
          cache_path: hub-mirror-cache
          timeout: '30m'
          debug: true

  sync-thTag:
    name: Sync thTag
    runs-on: ubuntu-latest
    steps:
      - name: Mirror thTag
        uses: Yikun/hub-mirror-action@ba51c01b28a6c9f95a25d4f1bcf6af2a147c0e18
        with:
          src: github/thTag
          dst: gitee/ya2
          src_account_type: org
          dst_account_type: user
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          src_token: ${{ secrets.SRC_TOKEN }}
          static_list: "docs"
          cache_path: hub-mirror-cache
          timeout: '30m'
          debug: true
