name: Sync to Gitee

on:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/sync-to-gitee.yml'
  workflow_dispatch:

concurrency:
  group: sync-to-gitee
  cancel-in-progress: false

jobs:
  sync-th-dd:
    name: Sync th-dd
    runs-on: ubuntu-latest
    steps:
      - name: Mirror th-dd
        uses: Yikun/hub-mirror-action@ba51c01b28a6c9f95a25d4f1bcf6af2a147c0e18
        with:
          src: github/th-dd
          dst: gitee/ya2
          src_account_type: user
          dst_account_type: user
          dst_key: ${{ secrets.GITEE_SSH }}
          dst_token: ${{ secrets.GITEE_PAT }}
          src_token: ${{ secrets.GH_PAT }}
          static_list: "th-dd,npmjs-chinese"
          mappings: "th-dd=>ya2"
          force_update: true
          cache_path: hub-mirror-cache
          timeout: '30m'

  sync-thTag:
    name: Sync thTag
    runs-on: ubuntu-latest
    steps:
      - name: Mirror thTag
        uses: Yikun/hub-mirror-action@ba51c01b28a6c9f95a25d4f1bcf6af2a147c0e18
        with:
          src: github/thTag
          dst: gitee/ya2
          src_account_type: org
          dst_account_type: user
          dst_key: ${{ secrets.GITEE_SSH }}
          dst_token: ${{ secrets.GITEE_PAT }}
          src_token: ${{ secrets.GH_PAT }}
          static_list: "docs"
          force_update: true
          cache_path: hub-mirror-cache
          timeout: '30m'
